version: '3.8'
services:
  db:
    image: postgis/postgis:latest
    env_file: .env
    ports:
      - "5432:5432"
  server:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
