version: '3.8'
services:
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
